# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "sd_mod" "sdhci_pci" ];
  boot.kernelModules = [ "kvm-intel" "wl" "msr" "coretemp" "applesmc" ];
  boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];

  boot.initrd.kernelModules = [ 
    "nls-cp437" # /boot
    "nls-iso8859-1" # /boot
    "vfat" # /boot
  ];
  boot.kernelPackages = pkgs.linuxPackages;
  boot.loader.systemd-boot.editor = false;
  boot.loader.timeout = 0;

  networking.hostName = "mini";
  networking.nameservers = [ "192.168.0.1" "8.8.8.8" "8.8.4.4" ];
  networking.networkmanager.enable = lib.mkForce true;
  networking.wireless.enable = lib.mkForce false;

  # Chromecast rules to let the UDP unicast packets pass to detect the devices.
  networking.firewall.extraCommands =
    ''
     iptables -I INPUT -p udp -m udp -s 192.168.1.7 --dport 32768:61000 -j ACCEPT 
     iptables -I INPUT -p udp -m udp -s 192.168.1.6 --dport 32768:61000 -j ACCEPT 
    '';


  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f434f98b-3198-48e5-bafa-e326108f47fa";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2860-11F4";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/5338d943-fe24-4b46-abe9-53b7aa75ddec"; }
    ];

  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = "powersave";
}
